apply_library_patches: true
bundled_packages_dir: packages
data_dir: data
description: null
environment_variables:
  OPENAI_API_KEY: null
external_package_dirs: []
python_version: py39
requirements:
- langchain
- openai
resources:
  accelerator: null
  cpu: 500m
  memory: 512Mi
  use_gpu: false
secrets: {}
spec_version: '2.0'
system_packages: []
